[package]
name = "exchange_outpost_abi"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
extism-pdk = "1.4.1"
serde = "1.0.219"
serde_json = "1.0.143"
rust_decimal = "1.37.2"

[profile.release]
strip = true  # Automatically strip symbols from the binary.